/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service descriptor
         * @description A small, human-readable JSON descriptor listing the service's endpoints.
         */
        get: operations["root_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations/{conversation_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Restore a conversation
         * @description Fetch a stored conversation's messages (oldest-first, bounded to the most recent 200) to rehydrate the chat widget after a page reload.
         */
        get: operations["chat_conversations_retrieve"];
        put?: never;
        post?: never;
        /**
         * Delete a conversation
         * @description Permanently delete a conversation and all its messages. The client should also drop its stored conversation id. Possessing the UUID is the check.
         */
        delete: operations["chat_conversations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Liveness probe used by the host's health check (Render) and uptime monitor.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Liveness probe used by the host's health check (Render) and uptime monitor.
         */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream an assistant reply (Server-Sent Events)
         * @description Runs the LangGraph agent and streams its reply as `text/event-stream`.
         *
         *     The body is `data: <json>\n\n` frames: first a `ChatConversationIdFrame`, then `ChatTextFrame` tokens interleaved with `ChatToolFrame` steps, and finally a `ChatDoneFrame` (or a `ChatErrorFrame` then done). Guarded by a per-IP rate limit and a message-length cap.
         */
        post: operations["chat_stream_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The stored conversation returned by the restore endpoint. */
        ConversationRestore: {
            /**
             * Format: uuid
             * @description The conversation's UUID.
             */
            id: string;
            /** @description Turns oldest-first. */
            messages: components["schemas"]["Message"][];
        };
        Health: {
            /** @description Always "ok" when the service is live. */
            status: string;
        };
        Message: {
            /**
             * @description "user" or "assistant".
             *
             *     * `user` - User
             *     * `assistant` - Assistant
             */
            role: components["schemas"]["RoleEnum"];
            content: string;
        };
        /**
         * @description * `user` - User
         *     * `assistant` - Assistant
         * @enum {string}
         */
        RoleEnum: "user" | "assistant";
        ServiceDescriptor: {
            service: string;
            status: string;
            endpoints: components["schemas"]["ServiceEndpoints"];
        };
        ServiceEndpoints: {
            health: string;
            docs: string;
            schema: string;
            chat_stream: string;
            analytics_proxy: string;
        };
        ChatStreamRequest: {
            /** @description The user's message. */
            message: string;
            /**
             * Format: uuid
             * @description Continue an existing thread; omit to start a new one.
             */
            conversation_id?: string | null;
        };
        /** @description Always the first frame — the id to continue the thread. */
        ChatConversationIdFrame: {
            /** Format: uuid */
            conversation_id: string;
        };
        /** @description A chunk of the assistant's answer. */
        ChatTextFrame: {
            text: string;
        };
        /** @description A tool step, for the frontend's activity animations. */
        ChatToolFrame: {
            /** @description Tool name, e.g. get_facts, get_cv, list_github_projects, get_repo_readme. */
            tool: string;
            /** @enum {string} */
            status: "start" | "end";
        };
        /** @description Sent only if every model failed before any text streamed. */
        ChatErrorFrame: {
            error: string;
        };
        /** @description Always the final frame. */
        ChatDoneFrame: {
            /** @enum {boolean} */
            done: true;
        };
        /** @description One Server-Sent Events frame. Each `data:` line is one of these. */
        ChatStreamFrame: components["schemas"]["ChatConversationIdFrame"] | components["schemas"]["ChatTextFrame"] | components["schemas"]["ChatToolFrame"] | components["schemas"]["ChatErrorFrame"] | components["schemas"]["ChatDoneFrame"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDescriptor"];
                };
            };
        };
    };
    chat_conversations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRestore"];
                };
            };
            /** @description Unknown or expired conversation — start fresh. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_conversations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown conversation. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    chat_stream_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatStreamRequest"];
            };
        };
        responses: {
            /** @description The SSE stream. Each frame is a `ChatStreamFrame`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatStreamFrame"];
                };
            };
            /** @description Missing/too-long message, or an invalid JSON body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-IP rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
